// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/flow.proto

package flowprotob

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FlowMessage_FlowType int32

const (
	FlowMessage_FLOWUNKNOWN FlowMessage_FlowType = 0
	FlowMessage_SFLOW_5     FlowMessage_FlowType = 1
	FlowMessage_NETFLOW_V5  FlowMessage_FlowType = 2
	FlowMessage_NETFLOW_V9  FlowMessage_FlowType = 3
	FlowMessage_IPFIX       FlowMessage_FlowType = 4
)

var FlowMessage_FlowType_name = map[int32]string{
	0: "FLOWUNKNOWN",
	1: "SFLOW_5",
	2: "NETFLOW_V5",
	3: "NETFLOW_V9",
	4: "IPFIX",
}

var FlowMessage_FlowType_value = map[string]int32{
	"FLOWUNKNOWN": 0,
	"SFLOW_5":     1,
	"NETFLOW_V5":  2,
	"NETFLOW_V9":  3,
	"IPFIX":       4,
}

func (x FlowMessage_FlowType) String() string {
	return proto.EnumName(FlowMessage_FlowType_name, int32(x))
}

func (FlowMessage_FlowType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0beab9b6746e934c, []int{0, 0}
}

type FlowMessage struct {
	Type          FlowMessage_FlowType `protobuf:"varint,1,opt,name=Type,proto3,enum=flowprotob.FlowMessage_FlowType" json:"Type,omitempty"`
	TimeReceived  uint64               `protobuf:"varint,2,opt,name=TimeReceived,proto3" json:"TimeReceived,omitempty"`
	SequenceNum   uint32               `protobuf:"varint,4,opt,name=SequenceNum,proto3" json:"SequenceNum,omitempty"`
	SamplingRate  uint64               `protobuf:"varint,3,opt,name=SamplingRate,proto3" json:"SamplingRate,omitempty"`
	FlowDirection uint32               `protobuf:"varint,42,opt,name=FlowDirection,proto3" json:"FlowDirection,omitempty"`
	// Sampler information
	SamplerAddress []byte `protobuf:"bytes,11,opt,name=SamplerAddress,proto3" json:"SamplerAddress,omitempty"`
	// Found inside packet
	TimeFlowStart uint64 `protobuf:"varint,38,opt,name=TimeFlowStart,proto3" json:"TimeFlowStart,omitempty"`
	TimeFlowEnd   uint64 `protobuf:"varint,5,opt,name=TimeFlowEnd,proto3" json:"TimeFlowEnd,omitempty"`
	// Size of the sampled packet
	Bytes   uint64 `protobuf:"varint,9,opt,name=Bytes,proto3" json:"Bytes,omitempty"`
	Packets uint64 `protobuf:"varint,10,opt,name=Packets,proto3" json:"Packets,omitempty"`
	// Source/destination addresses
	SrcAddr []byte `protobuf:"bytes,6,opt,name=SrcAddr,proto3" json:"SrcAddr,omitempty"`
	DstAddr []byte `protobuf:"bytes,7,opt,name=DstAddr,proto3" json:"DstAddr,omitempty"`
	// Layer 3 protocol (IPv4/IPv6/ARP/...)
	Etype uint32 `protobuf:"varint,30,opt,name=Etype,proto3" json:"Etype,omitempty"`
	// Layer 4 protocol
	Proto uint32 `protobuf:"varint,20,opt,name=Proto,proto3" json:"Proto,omitempty"`
	// Ports for UDP and TCP
	SrcPort uint32 `protobuf:"varint,21,opt,name=SrcPort,proto3" json:"SrcPort,omitempty"`
	DstPort uint32 `protobuf:"varint,22,opt,name=DstPort,proto3" json:"DstPort,omitempty"`
	// Interfaces
	SrcIf uint32 `protobuf:"varint,18,opt,name=SrcIf,proto3" json:"SrcIf,omitempty"`
	DstIf uint32 `protobuf:"varint,19,opt,name=DstIf,proto3" json:"DstIf,omitempty"`
	// Ethernet information
	SrcMac uint64 `protobuf:"varint,27,opt,name=SrcMac,proto3" json:"SrcMac,omitempty"`
	DstMac uint64 `protobuf:"varint,28,opt,name=DstMac,proto3" json:"DstMac,omitempty"`
	// Vlan
	SrcVlan uint32 `protobuf:"varint,33,opt,name=SrcVlan,proto3" json:"SrcVlan,omitempty"`
	DstVlan uint32 `protobuf:"varint,34,opt,name=DstVlan,proto3" json:"DstVlan,omitempty"`
	// 802.1q VLAN in sampled packet
	VlanId uint32 `protobuf:"varint,29,opt,name=VlanId,proto3" json:"VlanId,omitempty"`
	// VRF
	IngressVrfID uint32 `protobuf:"varint,39,opt,name=IngressVrfID,proto3" json:"IngressVrfID,omitempty"`
	EgressVrfID  uint32 `protobuf:"varint,40,opt,name=EgressVrfID,proto3" json:"EgressVrfID,omitempty"`
	// IP and TCP special flags
	IPTos                uint32 `protobuf:"varint,23,opt,name=IPTos,proto3" json:"IPTos,omitempty"`
	ForwardingStatus     uint32 `protobuf:"varint,24,opt,name=ForwardingStatus,proto3" json:"ForwardingStatus,omitempty"`
	IPTTL                uint32 `protobuf:"varint,25,opt,name=IPTTL,proto3" json:"IPTTL,omitempty"`
	TCPFlags             uint32 `protobuf:"varint,26,opt,name=TCPFlags,proto3" json:"TCPFlags,omitempty"`
	IcmpType             uint32 `protobuf:"varint,31,opt,name=IcmpType,proto3" json:"IcmpType,omitempty"`
	IcmpCode             uint32 `protobuf:"varint,32,opt,name=IcmpCode,proto3" json:"IcmpCode,omitempty"`
	IPv6FlowLabel        uint32 `protobuf:"varint,37,opt,name=IPv6FlowLabel,proto3" json:"IPv6FlowLabel,omitempty"`
	IPv6ExtensionHeaders uint32 `protobuf:"varint,43,opt,name=IPv6ExtensionHeaders,proto3" json:"IPv6ExtensionHeaders,omitempty"`
	// Fragments (IPv4/IPv6)
	FragmentId      uint32 `protobuf:"varint,35,opt,name=FragmentId,proto3" json:"FragmentId,omitempty"`
	FragmentOffset  uint32 `protobuf:"varint,36,opt,name=FragmentOffset,proto3" json:"FragmentOffset,omitempty"`
	BiFlowDirection uint32 `protobuf:"varint,41,opt,name=BiFlowDirection,proto3" json:"BiFlowDirection,omitempty"`
	// Autonomous system information
	SrcAS     uint32 `protobuf:"varint,14,opt,name=SrcAS,proto3" json:"SrcAS,omitempty"`
	DstAS     uint32 `protobuf:"varint,15,opt,name=DstAS,proto3" json:"DstAS,omitempty"`
	NextHop   []byte `protobuf:"bytes,12,opt,name=NextHop,proto3" json:"NextHop,omitempty"`
	NextHopAS uint32 `protobuf:"varint,13,opt,name=NextHopAS,proto3" json:"NextHopAS,omitempty"`
	// Prefix size
	SrcNet               uint32   `protobuf:"varint,16,opt,name=SrcNet,proto3" json:"SrcNet,omitempty"`
	DstNet               uint32   `protobuf:"varint,17,opt,name=DstNet,proto3" json:"DstNet,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlowMessage) Reset()         { *m = FlowMessage{} }
func (m *FlowMessage) String() string { return proto.CompactTextString(m) }
func (*FlowMessage) ProtoMessage()    {}
func (*FlowMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_0beab9b6746e934c, []int{0}
}

func (m *FlowMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlowMessage.Unmarshal(m, b)
}
func (m *FlowMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlowMessage.Marshal(b, m, deterministic)
}
func (m *FlowMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlowMessage.Merge(m, src)
}
func (m *FlowMessage) XXX_Size() int {
	return xxx_messageInfo_FlowMessage.Size(m)
}
func (m *FlowMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_FlowMessage.DiscardUnknown(m)
}

var xxx_messageInfo_FlowMessage proto.InternalMessageInfo

func (m *FlowMessage) GetType() FlowMessage_FlowType {
	if m != nil {
		return m.Type
	}
	return FlowMessage_FLOWUNKNOWN
}

func (m *FlowMessage) GetTimeReceived() uint64 {
	if m != nil {
		return m.TimeReceived
	}
	return 0
}

func (m *FlowMessage) GetSequenceNum() uint32 {
	if m != nil {
		return m.SequenceNum
	}
	return 0
}

func (m *FlowMessage) GetSamplingRate() uint64 {
	if m != nil {
		return m.SamplingRate
	}
	return 0
}

func (m *FlowMessage) GetFlowDirection() uint32 {
	if m != nil {
		return m.FlowDirection
	}
	return 0
}

func (m *FlowMessage) GetSamplerAddress() []byte {
	if m != nil {
		return m.SamplerAddress
	}
	return nil
}

func (m *FlowMessage) GetTimeFlowStart() uint64 {
	if m != nil {
		return m.TimeFlowStart
	}
	return 0
}

func (m *FlowMessage) GetTimeFlowEnd() uint64 {
	if m != nil {
		return m.TimeFlowEnd
	}
	return 0
}

func (m *FlowMessage) GetBytes() uint64 {
	if m != nil {
		return m.Bytes
	}
	return 0
}

func (m *FlowMessage) GetPackets() uint64 {
	if m != nil {
		return m.Packets
	}
	return 0
}

func (m *FlowMessage) GetSrcAddr() []byte {
	if m != nil {
		return m.SrcAddr
	}
	return nil
}

func (m *FlowMessage) GetDstAddr() []byte {
	if m != nil {
		return m.DstAddr
	}
	return nil
}

func (m *FlowMessage) GetEtype() uint32 {
	if m != nil {
		return m.Etype
	}
	return 0
}

func (m *FlowMessage) GetProto() uint32 {
	if m != nil {
		return m.Proto
	}
	return 0
}

func (m *FlowMessage) GetSrcPort() uint32 {
	if m != nil {
		return m.SrcPort
	}
	return 0
}

func (m *FlowMessage) GetDstPort() uint32 {
	if m != nil {
		return m.DstPort
	}
	return 0
}

func (m *FlowMessage) GetSrcIf() uint32 {
	if m != nil {
		return m.SrcIf
	}
	return 0
}

func (m *FlowMessage) GetDstIf() uint32 {
	if m != nil {
		return m.DstIf
	}
	return 0
}

func (m *FlowMessage) GetSrcMac() uint64 {
	if m != nil {
		return m.SrcMac
	}
	return 0
}

func (m *FlowMessage) GetDstMac() uint64 {
	if m != nil {
		return m.DstMac
	}
	return 0
}

func (m *FlowMessage) GetSrcVlan() uint32 {
	if m != nil {
		return m.SrcVlan
	}
	return 0
}

func (m *FlowMessage) GetDstVlan() uint32 {
	if m != nil {
		return m.DstVlan
	}
	return 0
}

func (m *FlowMessage) GetVlanId() uint32 {
	if m != nil {
		return m.VlanId
	}
	return 0
}

func (m *FlowMessage) GetIngressVrfID() uint32 {
	if m != nil {
		return m.IngressVrfID
	}
	return 0
}

func (m *FlowMessage) GetEgressVrfID() uint32 {
	if m != nil {
		return m.EgressVrfID
	}
	return 0
}

func (m *FlowMessage) GetIPTos() uint32 {
	if m != nil {
		return m.IPTos
	}
	return 0
}

func (m *FlowMessage) GetForwardingStatus() uint32 {
	if m != nil {
		return m.ForwardingStatus
	}
	return 0
}

func (m *FlowMessage) GetIPTTL() uint32 {
	if m != nil {
		return m.IPTTL
	}
	return 0
}

func (m *FlowMessage) GetTCPFlags() uint32 {
	if m != nil {
		return m.TCPFlags
	}
	return 0
}

func (m *FlowMessage) GetIcmpType() uint32 {
	if m != nil {
		return m.IcmpType
	}
	return 0
}

func (m *FlowMessage) GetIcmpCode() uint32 {
	if m != nil {
		return m.IcmpCode
	}
	return 0
}

func (m *FlowMessage) GetIPv6FlowLabel() uint32 {
	if m != nil {
		return m.IPv6FlowLabel
	}
	return 0
}

func (m *FlowMessage) GetIPv6ExtensionHeaders() uint32 {
	if m != nil {
		return m.IPv6ExtensionHeaders
	}
	return 0
}

func (m *FlowMessage) GetFragmentId() uint32 {
	if m != nil {
		return m.FragmentId
	}
	return 0
}

func (m *FlowMessage) GetFragmentOffset() uint32 {
	if m != nil {
		return m.FragmentOffset
	}
	return 0
}

func (m *FlowMessage) GetBiFlowDirection() uint32 {
	if m != nil {
		return m.BiFlowDirection
	}
	return 0
}

func (m *FlowMessage) GetSrcAS() uint32 {
	if m != nil {
		return m.SrcAS
	}
	return 0
}

func (m *FlowMessage) GetDstAS() uint32 {
	if m != nil {
		return m.DstAS
	}
	return 0
}

func (m *FlowMessage) GetNextHop() []byte {
	if m != nil {
		return m.NextHop
	}
	return nil
}

func (m *FlowMessage) GetNextHopAS() uint32 {
	if m != nil {
		return m.NextHopAS
	}
	return 0
}

func (m *FlowMessage) GetSrcNet() uint32 {
	if m != nil {
		return m.SrcNet
	}
	return 0
}

func (m *FlowMessage) GetDstNet() uint32 {
	if m != nil {
		return m.DstNet
	}
	return 0
}

func init() {
	proto.RegisterEnum("flowprotob.FlowMessage_FlowType", FlowMessage_FlowType_name, FlowMessage_FlowType_value)
	proto.RegisterType((*FlowMessage)(nil), "flowprotob.FlowMessage")
}

func init() { proto.RegisterFile("pb/flow.proto", fileDescriptor_0beab9b6746e934c) }

var fileDescriptor_0beab9b6746e934c = []byte{
	// 717 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x94, 0x6f, 0x53, 0xda, 0x4a,
	0x14, 0xc6, 0x2f, 0x8a, 0xa8, 0x8b, 0x20, 0x77, 0xaf, 0xd7, 0x7b, 0xae, 0xb5, 0x96, 0x52, 0x6b,
	0xa9, 0xce, 0xd0, 0x19, 0x5b, 0x3b, 0xd3, 0x97, 0x20, 0x30, 0x66, 0x8a, 0xc8, 0x10, 0xaa, 0x7d,
	0xd7, 0x09, 0xc9, 0x92, 0xc9, 0x34, 0x24, 0x34, 0xbb, 0xf8, 0xe7, 0x8b, 0xf6, 0xf3, 0x74, 0xce,
	0xd9, 0x0d, 0x06, 0xdb, 0x57, 0xec, 0xf3, 0x7b, 0x0e, 0x27, 0x67, 0x67, 0x9f, 0x5d, 0x56, 0x9a,
	0x8d, 0xdf, 0x4d, 0xc2, 0xf8, 0xae, 0x31, 0x4b, 0x62, 0x15, 0x73, 0x86, 0x6b, 0x5a, 0x8e, 0x6b,
	0x3f, 0x19, 0x2b, 0x76, 0xc3, 0xf8, 0xee, 0x52, 0x48, 0xe9, 0xf8, 0x82, 0x7f, 0x60, 0xf9, 0xd1,
	0xc3, 0x4c, 0x40, 0xae, 0x9a, 0xab, 0x97, 0x4f, 0xab, 0x8d, 0xc7, 0xd2, 0x46, 0xa6, 0x8c, 0xd6,
	0x58, 0x37, 0xa4, 0x6a, 0x5e, 0x63, 0x5b, 0xa3, 0x60, 0x2a, 0x86, 0xc2, 0x15, 0xc1, 0xad, 0xf0,
	0x60, 0xa5, 0x9a, 0xab, 0xe7, 0x87, 0x4b, 0x8c, 0x57, 0x59, 0xd1, 0x16, 0x3f, 0xe6, 0x22, 0x72,
	0x45, 0x7f, 0x3e, 0x85, 0x7c, 0x35, 0x57, 0x2f, 0x0d, 0xb3, 0x08, 0xbb, 0xd8, 0xce, 0x74, 0x16,
	0x06, 0x91, 0x3f, 0x74, 0x94, 0x80, 0x55, 0xdd, 0x25, 0xcb, 0xf8, 0x21, 0x2b, 0xe1, 0xb7, 0xdb,
	0x41, 0x22, 0x5c, 0x15, 0xc4, 0x11, 0x1c, 0x53, 0x9f, 0x65, 0xc8, 0x8f, 0x58, 0x99, 0xfe, 0x25,
	0x92, 0xa6, 0xe7, 0x25, 0x42, 0x4a, 0x28, 0x56, 0x73, 0xf5, 0xad, 0xe1, 0x13, 0x8a, 0xdd, 0x70,
	0x46, 0xfc, 0xb3, 0xad, 0x9c, 0x44, 0xc1, 0x11, 0x7d, 0x72, 0x19, 0xe2, 0xe4, 0x29, 0xe8, 0x44,
	0x1e, 0xac, 0x51, 0x4d, 0x16, 0xf1, 0x1d, 0xb6, 0xd6, 0x7a, 0x50, 0x42, 0xc2, 0x26, 0x79, 0x5a,
	0x70, 0x60, 0xeb, 0x03, 0xc7, 0xfd, 0x2e, 0x94, 0x04, 0x46, 0x3c, 0x95, 0xe8, 0xd8, 0x89, 0x8b,
	0x53, 0x40, 0x81, 0x06, 0x4b, 0x25, 0x3a, 0x6d, 0xa9, 0xc8, 0x59, 0xd7, 0x8e, 0x91, 0xf8, 0x8d,
	0x8e, 0xc2, 0xa3, 0x39, 0xa0, 0x1d, 0x6b, 0x81, 0x74, 0x80, 0xc7, 0x03, 0x3b, 0x9a, 0x92, 0x30,
	0xfd, 0x07, 0x71, 0xa2, 0xe0, 0x5f, 0xe2, 0xa9, 0x34, 0xfd, 0xc9, 0xd9, 0xd5, 0x8e, 0x91, 0xd8,
	0xc9, 0x4e, 0x5c, 0x6b, 0x02, 0x5c, 0x77, 0x22, 0x81, 0xb4, 0x2d, 0x95, 0x35, 0x81, 0x7f, 0x34,
	0x25, 0xc1, 0x77, 0x59, 0xc1, 0x4e, 0xdc, 0x4b, 0xc7, 0x85, 0x67, 0xb4, 0x31, 0xa3, 0x90, 0xb7,
	0xa5, 0x42, 0xbe, 0xaf, 0xb9, 0x56, 0x66, 0x9e, 0xeb, 0xd0, 0x89, 0xe0, 0xe5, 0x62, 0x1e, 0x94,
	0x66, 0x1e, 0x72, 0x6a, 0x8b, 0x79, 0xc8, 0xd9, 0x65, 0x05, 0xfc, 0xb5, 0x3c, 0x78, 0x4e, 0x86,
	0x51, 0x98, 0x12, 0x2b, 0xf2, 0xf1, 0xf8, 0xae, 0x93, 0x89, 0xd5, 0x86, 0x37, 0xe4, 0x2e, 0x31,
	0x3c, 0xb1, 0x4e, 0xa6, 0xa4, 0xae, 0xb3, 0x96, 0x41, 0xb8, 0x2f, 0x6b, 0x30, 0x8a, 0x25, 0xfc,
	0xa7, 0xf7, 0x45, 0x82, 0x1f, 0xb3, 0x4a, 0x37, 0x4e, 0xee, 0x9c, 0xc4, 0x0b, 0x22, 0xdf, 0x56,
	0x8e, 0x9a, 0x4b, 0x00, 0x2a, 0xf8, 0x8d, 0x9b, 0x0e, 0xa3, 0x1e, 0xfc, 0xbf, 0xe8, 0x30, 0xea,
	0xf1, 0x3d, 0xb6, 0x31, 0x3a, 0x1f, 0x74, 0x43, 0xc7, 0x97, 0xb0, 0x47, 0xc6, 0x42, 0xa3, 0x67,
	0xb9, 0xd3, 0x19, 0xdd, 0xaf, 0x17, 0xda, 0x4b, 0x75, 0xea, 0x9d, 0xc7, 0x9e, 0x80, 0xea, 0xa3,
	0x87, 0x1a, 0x53, 0x6a, 0x0d, 0x6e, 0x3f, 0x62, 0xd8, 0x7a, 0xce, 0x58, 0x84, 0xf0, 0x5a, 0x67,
	0x7e, 0x09, 0xf2, 0x53, 0xb6, 0x83, 0xa0, 0x73, 0xaf, 0x44, 0x24, 0x83, 0x38, 0xba, 0x10, 0x8e,
	0x27, 0x12, 0x09, 0x27, 0x54, 0xfc, 0x47, 0x8f, 0x1f, 0x30, 0xd6, 0x4d, 0x1c, 0x7f, 0x2a, 0x22,
	0x65, 0x79, 0xf0, 0x8a, 0x2a, 0x33, 0x04, 0xef, 0x51, 0xaa, 0xae, 0x26, 0x13, 0x29, 0x14, 0x1c,
	0x52, 0xcd, 0x13, 0xca, 0xeb, 0x6c, 0xbb, 0x15, 0x2c, 0xdf, 0xcb, 0xb7, 0x54, 0xf8, 0x14, 0x9b,
	0x94, 0x35, 0x6d, 0x28, 0x2f, 0x52, 0xd6, 0xb4, 0x4d, 0xca, 0x9a, 0x36, 0x6c, 0x2f, 0x52, 0xd6,
	0xb4, 0x31, 0x1b, 0x7d, 0x71, 0xaf, 0x2e, 0xe2, 0x19, 0x6c, 0xe9, 0xbb, 0x60, 0x24, 0xdf, 0x67,
	0x9b, 0x66, 0xd9, 0xb4, 0xa1, 0x44, 0xff, 0x79, 0x04, 0x26, 0x9d, 0x7d, 0xa1, 0xa0, 0xa2, 0x93,
	0xa3, 0x95, 0x49, 0x27, 0xf2, 0xbf, 0x35, 0xd7, 0xaa, 0x66, 0xb3, 0x8d, 0xf4, 0x3d, 0xe3, 0xdb,
	0xac, 0xd8, 0xed, 0x5d, 0xdd, 0x7c, 0xe9, 0x7f, 0xee, 0x5f, 0xdd, 0xf4, 0x2b, 0x7f, 0xf1, 0x22,
	0x5b, 0xb7, 0x91, 0x7c, 0x3b, 0xab, 0xe4, 0x78, 0x99, 0xb1, 0x7e, 0x67, 0x44, 0xf2, 0xfa, 0xac,
	0xb2, 0xb2, 0xa4, 0x3f, 0x55, 0x56, 0xf9, 0x26, 0x66, 0xa2, 0x6b, 0x7d, 0xad, 0xe4, 0x5b, 0x27,
	0x6c, 0xcf, 0x8d, 0xa7, 0x0d, 0x37, 0x8c, 0xe7, 0xde, 0x24, 0x74, 0x12, 0xd1, 0x88, 0x84, 0xa2,
	0xe7, 0xd4, 0xf1, 0xfd, 0x56, 0x29, 0xf3, 0x98, 0x0e, 0xc6, 0xe3, 0x02, 0x3d, 0xb1, 0xef, 0x7f,
	0x05, 0x00, 0x00, 0xff, 0xff, 0x79, 0xcd, 0x1b, 0x99, 0xa9, 0x05, 0x00, 0x00,
}
